name: CI/CD Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |

            echo " Deploy starting..."

            cd /home/arc/Auto_Deploy_Prj

            echo " Syncing code..."
            git fetch origin
            git reset --hard origin/main

            echo " Stopping containers..."
            docker compose down

            echo " Building..."
            docker compose up -d --build

            echo "✅ Done!"